### ISSUE TITLE
Street or satellite images cannot be downloaded

### ISSUE THREAD

**Issue by SergioBic** [nonta1234/terraining-heightmap-generator#44]
For example, if you click on IMG -> Street to download a street image, nothing happens. The same applies to all image selections. I have tried Chrome and MS Edge, both give the same result.

**Comment by nonta1234** [comment]
Could you please upload the settings json file?

**Comment by SergioBic** [comment]
Here you go:
[terraining-settings.json](https://github.com/user-attachments/files/18310440/terraining-settings.json)

**Comment by nonta1234** [comment]
I was able to download the map images without any problems with your settings.json.
Are there any errors displayed in the console?

**Comment by BL-Mtl** [comment]
Hi! I have the same situation...

Using Safari.

Here is the json file...
[terraining-settings.json](https://github.com/user-attachments/files/18310931/terraining-settings.json)

**Comment by SergioBic** [comment]
> I was able to download the map images without any problems with your settings.json. Are there any errors displayed in the console?

Chrome console:
--
Failed to evaluate expression "["all",["has","reflen"],["<=",["number",["get","reflen"]],6],["match",["get","class"],["pedestrian","service"],false,true],["step",["zoom"],["==",["geometry-type"],"Point"],11,[">",["number",["get","len"]],5000],12,[">",["number",["get","len"]],2500],13,[">",["number",["get","len"]],1000],14,true]]". The expression ["get","len"] evaluated to null but was expected to be of type number.
--
Access to fetch at 'https://api.mapbox.com/styles/v1/mapbox/streets-v12/static/[14.000662498398292,42.3081399708087,14.305224313527262,42.53297119221474]/1280x1280@2x?access_token=' from origin 'https://terraining.ateliernonta.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
--
GET https://api.mapbox.com/styles/v1/mapbox/streets-v12/static/[14.000662498398292,42.3081399708087,14.305224313527262,42.53297119221474]/1280x1280@2x?access_token= net::ERR_FAILED 401 (Unauthorized)
--
An error occurred in getMapImage: TypeError: Failed to fetch
    at pw (EssVJPco.js:744:48915)
    at m (EssVJPco.js:744:52249)
    at Fi (EssVJPco.js:13:38)
    at sr (EssVJPco.js:13:109)
    at nE (EssVJPco.js:13:40417)
    at I (EssVJPco.js:577:23041)
    at he (EssVJPco.js:577:24982)
    at onClick (EssVJPco.js:577:27210)
    at Fi (EssVJPco.js:13:38)
    at sr (EssVJPco.js:13:109)
--
TypeError: Failed to fetch
    at pw (EssVJPco.js:744:48915)
    at m (EssVJPco.js:744:52249)
    at Fi (EssVJPco.js:13:38)
    at sr (EssVJPco.js:13:109)
    at nE (EssVJPco.js:13:40417)
    at I (EssVJPco.js:577:23041)
    at he (EssVJPco.js:577:24982)
    at onClick (EssVJPco.js:577:27210)
    at Fi (EssVJPco.js:13:38)
    at sr (EssVJPco.js:13:109)

**Comment by BL-Mtl** [comment]
I have the same errors messages on Safari's console.

**Comment by Gunner23b** [comment]
Same issue, can download PNG but cannot download any of the IMG options, get same error as above.  Tried in Chrome, Bing, and Firefox.

**Comment by OmegaGG** [comment]
+1 on this issue

**Comment by SevenDean** [comment]
+1 on this issue
[terraining-settings.json](https://github.com/user-attachments/files/18318969/terraining-settings.json)

**Comment by Bumerr** [comment]
Site is blocked to access mapbox api, afaik site need mapbox token again

**Comment by nonta1234** [comment]
It was a simple mistake. I fixed it, so I think it's fine.

**Comment by BL-Mtl** [comment]
> It was a simple mistake. I fixed it, so I think it's fine.

Yes it worked for me. Thanks so much!

**Comment by Gunner23b** [comment]
> Same issue, can download PNG but cannot download any of the IMG options, get same error as above. Tried in Chrome, Bing, and Firefox.

Works now, thanks!

**Comment by SergioBic** [comment]
It still doesn't work for me. It looks like I still need mapbox, in addition to maptiles.. If that's the case, why don't you specify it?

![image](https://github.com/user-attachments/assets/2ec91557-933d-4942-b783-8af86b926fd0)

**Comment by SevenDean** [comment]
Well, the good news is that the problem has been inexplicably solved. I do not know the cause of the problem, and I have not done anything to deal with it. Maybe it's my own network?

**Comment by nonta1234** [comment]
If it was a map image issue, it was a simple coding mistake. I'm glad it worked out.
